# Generated by Django 3.2.3 on 2021-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=200)),
                ('equacao', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('variaveis', models.CharField(max_length=200)),
                ('grandezas', models.CharField(max_length=200)),
                ('unidades', models.CharField(max_length=200)),
                ('equacoes', models.CharField(max_length=200)),
            ],
        ),
    ]
