# Generated by Django 3.2.4 on 2021-07-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.area'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='enunciado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='equacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='equacoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='grandezas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='unidades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='variaveis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
