# Generated by Django 3.2.5 on 2021-07-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210705_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now=True)),
                ('enunciado', models.TextField()),
                ('gabarito', models.CharField(max_length=100)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionmodel')),
            ],
        ),
    ]
