# Generated by Django 3.2.5 on 2021-07-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionmodel_area_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='area_nome',
        ),
    ]
