# Generated by Django 3.2.5 on 2021-07-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_questionmodel_area_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciados', models.JSONField()),
                ('gabarito', models.JSONField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.area')),
            ],
        ),
    ]
