# Generated by Django 3.2.5 on 2021-08-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now=True)),
                ('enunciados', models.JSONField()),
                ('gabaritos', models.JSONField()),
            ],
        ),
    ]
