# Generated by Django 3.2.5 on 2021-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_customquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='icon',
            field=models.ImageField(null=True, blank=True),
        ),
    ]
